# Generated by OmopViewer 0.2.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hds_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    "Commonly used antibiotics"
  ),
  theme = bslib::bs_theme(
    bootswatch = "sandstone",
    primary = "#605ca8",
    bg = "white",
    fg = "black",
    success = "#3B9AB2",
  ),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    summaryCard(data)
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$summarise_omop_snapshot_grouping_cdm_name,
              selected = filterValues$summarise_omop_snapshot_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_variable_name",
              label = "Variable name",
              choices = filterValues$summarise_omop_snapshot_variable_name,
              selected = filterValues$summarise_omop_snapshot_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_estimate_name",
              label = "Estimate name",
              choices = filterValues$summarise_omop_snapshot_estimate_name,
              selected = filterValues$summarise_omop_snapshot_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_tidy_columns",
                  label = "Columns",
                  choices = filterValues$summarise_omop_snapshot_tidy_columns,
                  selected = filterValues$summarise_omop_snapshot_tidy_columns,
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::radioButtons(
                  inputId = "summarise_omop_snapshot_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_omop_snapshot_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Snapshot table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_gt_17_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_17_download", label = "Download")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_omop_snapshot_gt_17")
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Observation period",
    icon = shiny::icon("eye"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$summarise_observation_period_grouping_cdm_name,
              selected = filterValues$summarise_observation_period_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_grouping_observation_period_ordinal",
              label = "Observation period ordinal",
              choices = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
              selected = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_variable_name",
              label = "Variable name",
              choices = filterValues$summarise_observation_period_variable_name,
              selected = filterValues$summarise_observation_period_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "summarise_observation_period_estimate_name",
              label = "Estimate name",
              choices = filterValues$summarise_observation_period_estimate_name,
              selected = filterValues$summarise_observation_period_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_observation_period_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_tidy_columns",
                  label = "Columns",
                  choices = filterValues$summarise_observation_period_tidy_columns,
                  selected = filterValues$summarise_observation_period_tidy_columns,
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::radioButtons(
                  inputId = "summarise_observation_period_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("summarise_observation_period_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Table observation period",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_gt_15_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_observation_period_gt_15_download", label = "Download")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_observation_period_gt_15")
          )
        ),
        bslib::nav_panel(
          title = "Plot observation period",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_height",
                  label = "Height",
                  value = 10
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_units",
                  label = "Units",
                  selected = "cm",
                  choices = c("px", "cm", "inch"),
                  multiple = FALSE
                ),
                shiny::numericInput(
                  inputId = "summarise_observation_period_ggplot2_16_download_dpi",
                  label = "dpi",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_observation_period_ggplot2_16_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_variableName",
                  label = "variableName",
                  selected = "number subjects",
                  multiple = ,
                  choices = c("number subjects", "records per person", "duration in days", "days to next observation period"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_plotType",
                  label = "plotType",
                  selected = "barplot",
                  multiple = ,
                  choices = c("barplot", "boxplot", "densityplot"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_observation_period_ggplot2_16_facet",
                  label = "facet",
                  selected = NULL,
                  multiple = TRUE,
                  choices = c("cdm_name", "observation_period_ordinal"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::plotOutput("summarise_observation_period_ggplot2_16")
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Incidence",
    icon = shiny::icon("chart-line"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Settings",
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_analysis_complete_database_intervals",
              label = "Analysis complete database intervals",
              choices = filterValues$incidence_settings_analysis_complete_database_intervals,
              selected = filterValues$incidence_settings_analysis_complete_database_intervals,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_analysis_outcome_washout",
              label = "Analysis outcome washout",
              choices = filterValues$incidence_settings_analysis_outcome_washout,
              selected = filterValues$incidence_settings_analysis_outcome_washout,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_analysis_repeated_events",
              label = "Analysis repeated events",
              choices = filterValues$incidence_settings_analysis_repeated_events,
              selected = filterValues$incidence_settings_analysis_repeated_events,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_denominator_age_group",
              label = "Denominator age group",
              choices = filterValues$incidence_settings_denominator_age_group,
              selected = filterValues$incidence_settings_denominator_age_group,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_denominator_days_prior_observation",
              label = "Denominator days prior observation",
              choices = filterValues$incidence_settings_denominator_days_prior_observation,
              selected = filterValues$incidence_settings_denominator_days_prior_observation,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_denominator_end_date",
              label = "Denominator end date",
              choices = filterValues$incidence_settings_denominator_end_date,
              selected = filterValues$incidence_settings_denominator_end_date,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_denominator_sex",
              label = "Denominator sex",
              choices = filterValues$incidence_settings_denominator_sex,
              selected = filterValues$incidence_settings_denominator_sex,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_denominator_start_date",
              label = "Denominator start date",
              choices = filterValues$incidence_settings_denominator_start_date,
              selected = filterValues$incidence_settings_denominator_start_date,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_denominator_target_cohort_name",
              label = "Denominator target cohort name",
              choices = filterValues$incidence_settings_denominator_target_cohort_name,
              selected = filterValues$incidence_settings_denominator_target_cohort_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_settings_denominator_time_at_risk",
              label = "Denominator time at risk",
              choices = filterValues$incidence_settings_denominator_time_at_risk,
              selected = filterValues$incidence_settings_denominator_time_at_risk,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "incidence_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$incidence_grouping_cdm_name,
              selected = filterValues$incidence_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_grouping_denominator_cohort_name",
              label = "Denominator cohort name",
              choices = filterValues$incidence_grouping_denominator_cohort_name,
              selected = filterValues$incidence_grouping_denominator_cohort_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_grouping_outcome_cohort_name",
              label = "Outcome cohort name",
              choices = filterValues$incidence_grouping_outcome_cohort_name,
              selected = filterValues$incidence_grouping_outcome_cohort_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_grouping_incidence_start_date",
              label = "Incidence start date",
              choices = filterValues$incidence_grouping_incidence_start_date,
              selected = filterValues$incidence_grouping_incidence_start_date,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_grouping_incidence_end_date",
              label = "Incidence end date",
              choices = filterValues$incidence_grouping_incidence_end_date,
              selected = filterValues$incidence_grouping_incidence_end_date,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_grouping_analysis_interval",
              label = "Analysis interval",
              choices = filterValues$incidence_grouping_analysis_interval,
              selected = filterValues$incidence_grouping_analysis_interval,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "incidence_variable_name",
              label = "Variable name",
              choices = filterValues$incidence_variable_name,
              selected = filterValues$incidence_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "incidence_estimate_name",
              label = "Estimate name",
              choices = filterValues$incidence_estimate_name,
              selected = filterValues$incidence_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "incidence_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "incidence_tidy_columns",
                  label = "Columns",
                  choices = filterValues$incidence_tidy_columns,
                  selected = filterValues$incidence_tidy_columns,
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::radioButtons(
                  inputId = "incidence_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("incidence_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Table incidence",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "incidence_gt_18_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "incidence_gt_18_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "none",
                    labels = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level"),
                    input_id = "incidence_gt_18_none"
                  ),
                  sortable::add_rank_list(
                    text = "header",
                    labels = "estimate_name",
                    input_id = "incidence_gt_18_header"
                  ),
                  sortable::add_rank_list(
                    text = "groupColumn",
                    labels = character(),
                    input_id = "incidence_gt_18_groupColumn"
                  ),
                  sortable::add_rank_list(
                    text = "hide",
                    labels = character(),
                    input_id = "incidence_gt_18_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("incidence_gt_18")
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot incidence",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "incidence_ggplot2_19_download_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "incidence_ggplot2_19_download_height",
                  label = "Height",
                  value = 10
                ),
                shinyWidgets::pickerInput(
                  inputId = "incidence_ggplot2_19_download_units",
                  label = "Units",
                  selected = "cm",
                  choices = c("px", "cm", "inch"),
                  multiple = FALSE
                ),
                shiny::numericInput(
                  inputId = "incidence_ggplot2_19_download_dpi",
                  label = "dpi",
                  value = 300
                ),
                shiny::downloadButton(outputId = "incidence_ggplot2_19_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "incidence_ggplot2_19_x",
                  label = "x",
                  selected = "incidence_start_date",
                  multiple = FALSE,
                  choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "incidence_ggplot2_19_ribbon",
                  label = "ribbon",
                  value = c(FALSE)
                ),
                shinyWidgets::pickerInput(
                  inputId = "incidence_ggplot2_19_facet",
                  label = "facet",
                  selected = NULL,
                  multiple = TRUE,
                  choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "incidence_ggplot2_19_colour",
                  label = "colour",
                  selected = NULL,
                  multiple = TRUE,
                  choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::plotOutput("incidence_ggplot2_19")
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Incidence attrition",
    icon = shiny::icon("layer-group"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Settings",
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_analysis_complete_database_intervals",
              label = "Analysis complete database intervals",
              choices = filterValues$incidence_attrition_settings_analysis_complete_database_intervals,
              selected = filterValues$incidence_attrition_settings_analysis_complete_database_intervals,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_analysis_outcome_washout",
              label = "Analysis outcome washout",
              choices = filterValues$incidence_attrition_settings_analysis_outcome_washout,
              selected = filterValues$incidence_attrition_settings_analysis_outcome_washout,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_analysis_repeated_events",
              label = "Analysis repeated events",
              choices = filterValues$incidence_attrition_settings_analysis_repeated_events,
              selected = filterValues$incidence_attrition_settings_analysis_repeated_events,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_denominator_age_group",
              label = "Denominator age group",
              choices = filterValues$incidence_attrition_settings_denominator_age_group,
              selected = filterValues$incidence_attrition_settings_denominator_age_group,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_denominator_days_prior_observation",
              label = "Denominator days prior observation",
              choices = filterValues$incidence_attrition_settings_denominator_days_prior_observation,
              selected = filterValues$incidence_attrition_settings_denominator_days_prior_observation,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_denominator_end_date",
              label = "Denominator end date",
              choices = filterValues$incidence_attrition_settings_denominator_end_date,
              selected = filterValues$incidence_attrition_settings_denominator_end_date,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_denominator_sex",
              label = "Denominator sex",
              choices = filterValues$incidence_attrition_settings_denominator_sex,
              selected = filterValues$incidence_attrition_settings_denominator_sex,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_denominator_start_date",
              label = "Denominator start date",
              choices = filterValues$incidence_attrition_settings_denominator_start_date,
              selected = filterValues$incidence_attrition_settings_denominator_start_date,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_denominator_target_cohort_name",
              label = "Denominator target cohort name",
              choices = filterValues$incidence_attrition_settings_denominator_target_cohort_name,
              selected = filterValues$incidence_attrition_settings_denominator_target_cohort_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_settings_denominator_time_at_risk",
              label = "Denominator time at risk",
              choices = filterValues$incidence_attrition_settings_denominator_time_at_risk,
              selected = filterValues$incidence_attrition_settings_denominator_time_at_risk,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$incidence_attrition_grouping_cdm_name,
              selected = filterValues$incidence_attrition_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_grouping_denominator_cohort_name",
              label = "Denominator cohort name",
              choices = filterValues$incidence_attrition_grouping_denominator_cohort_name,
              selected = filterValues$incidence_attrition_grouping_denominator_cohort_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_grouping_outcome_cohort_name",
              label = "Outcome cohort name",
              choices = filterValues$incidence_attrition_grouping_outcome_cohort_name,
              selected = filterValues$incidence_attrition_grouping_outcome_cohort_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_grouping_reason",
              label = "Reason",
              choices = filterValues$incidence_attrition_grouping_reason,
              selected = filterValues$incidence_attrition_grouping_reason,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_grouping_reason_id",
              label = "Reason id",
              choices = filterValues$incidence_attrition_grouping_reason_id,
              selected = filterValues$incidence_attrition_grouping_reason_id,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_variable_name",
              label = "Variable name",
              choices = filterValues$incidence_attrition_variable_name,
              selected = filterValues$incidence_attrition_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "incidence_attrition_estimate_name",
              label = "Estimate name",
              choices = filterValues$incidence_attrition_estimate_name,
              selected = filterValues$incidence_attrition_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "incidence_attrition_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "incidence_attrition_tidy_columns",
                  label = "Columns",
                  choices = filterValues$incidence_attrition_tidy_columns,
                  selected = filterValues$incidence_attrition_tidy_columns,
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::radioButtons(
                  inputId = "incidence_attrition_tidy_pivot",
                  label = "Pivot estimates/variables",
                  choices = c("none", "estimates", "estimates and variables"),
                  selected = "none"
                ),
                position = "right"
              ),
              DT::dataTableOutput("incidence_attrition_tidy")
            )
          )
        ),
        bslib::nav_panel(
          title = "Table incidence attrition",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "incidence_attrition_gt_22_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "incidence_attrition_gt_22_download", label = "Download")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "none",
                    labels = c("denominator_cohort_name", "outcome_cohort_name", "reason", "reason_id", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    input_id = "incidence_attrition_gt_22_none"
                  ),
                  sortable::add_rank_list(
                    text = "header",
                    labels = "variable_name",
                    input_id = "incidence_attrition_gt_22_header"
                  ),
                  sortable::add_rank_list(
                    text = "groupColumn",
                    labels = c("cdm_name", "variable_level"),
                    input_id = "incidence_attrition_gt_22_groupColumn"
                  ),
                  sortable::add_rank_list(
                    text = "hide",
                    labels = "estimate_name",
                    input_id = "incidence_attrition_gt_22_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("incidence_attrition_gt_22")
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.2.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
