---
title: "Report"
format: html
---

# Use of antibiotics commonly associated with antimicrobial resistance

```{r get data, echo=FALSE, message = FALSE, warning = FALSE}
resultList <- list(
  "summarise_omop_snapshot",
  "summarise_observation_period",
  "summarise_cohort_count",
  "cohort_code_use",
  "summarise_cohort_attrition",
  "summarise_characteristics",
  "summarise_large_scale_characteristics",
  "incidence",
  "incidence_attrition",
  "summarise_drug_utilisation"
)

source(file.path(getwd(), "functions.R"))

data_path <- file.path(getwd(), "data")
csv_files <- list.files(data_path, pattern = "\\.csv$", full.names = TRUE)

result <- purrr::map(csv_files, \(x){
  d <- omopgenerics::importSummarisedResult(x)  
  d
}) |> 
  omopgenerics::bind() |>
  omopgenerics::newSummarisedResult() |>
  dplyr::mutate(cdm_name = dplyr::case_when(
    cdm_name == "IDRIL_1" ~ "Lancashire",
    cdm_name == "LTHT" ~ "Leeds",
    cdm_name == "Barts Health" ~ "Barts",
    cdm_name == "AurumCDM_202409" ~ "CPRD Aurum",
    cdm_name == "GOSH DRE" ~ "GOSH",
    .default = cdm_name
  ))

result$additional_level <- gsub("&&&\\s+&&&", "&&& NULL &&&", result$additional_level)

resultList <- resultList |>
  purrr::map(\(x) {
    omopgenerics::settings(result) |>
      dplyr::filter(.data$result_type %in% .env$x) |>
      dplyr::pull(.data$result_id) }) |>
  rlang::set_names(resultList)

data <- prepareResult(result, resultList)
```

## Table 1 - Database descriptions

```{r db desc, echo=FALSE, message = FALSE, warning = FALSE}
snap <- data[["summarise_omop_snapshot"]] 

OmopSketch::tableOmopSnapshot(snap, type = "flextable")
```

## Table 2 - Patient characteristics 

```{r table 2, echo=FALSE, message = FALSE, warning = FALSE}
char <- data[["summarise_characteristics"]] |>
  dplyr::filter(!variable_name %in% c("Antibiotics (-90 to -15)", "Antibiotics (-14 to -1)", "Indication flag"),
                strata_level == "overall") |>
  dplyr::mutate(group_level = stringr::str_replace(group_level, "^\\d+_", ""),        
   group_level = stringr::str_to_sentence(group_level),
  ) |>
  dplyr::filter(group_level %in% c("Ciprofloxacin", "Clarithromycin", "Erythromycin", "Fusidate")) |>
  dplyr::filter(variable_name %in% c("Number records", "Number subjects", "Cohort start date", "Age", "Sex"),
                !estimate_name %in% c("mean", "sd")) |>
  dplyr::filter(variable_name != "Sex" | variable_level %in% c("Male", "Female"),
                variable_name != "Cohort start date" | estimate_name %in% c("min", "max"),
                cdm_name == "CPRD Aurum"
)

CohortCharacteristics::tableCharacteristics(char, type = "flextable", header = c("cohort_name"), groupColumn = c("cdm_name"), hide = c("age_group_broad", "table_name", "value", "table", "window"))
```

## Table 3 

```{r table 2, echo=FALSE, message = FALSE, warning = FALSE}
char <- data[["summarise_characteristics"]] |>
  dplyr::filter(!variable_name %in% c("Antibiotics (-90 to -15)", "Antibiotics (-14 to -1)", "Indication flag"),
                strata_level == "overall") |>
  dplyr::mutate(group_level = stringr::str_replace(group_level, "^\\d+_", ""),        
   group_level = stringr::str_to_sentence(group_level),
  ) |>
  dplyr::filter(group_level %in% c("Ciprofloxacin", "Clarithromycin", "Piperacillin", "Ceftriaxone",
                                   "Teicoplanin", "Vancomycin", "Cefuroxime")) |>
  dplyr::filter(variable_name %in% c("Number records", "Number subjects", "Cohort start date", "Age", "Sex"),
                !estimate_name %in% c("mean", "sd")) |>
  dplyr::filter(variable_name != "Sex" | variable_level %in% c("Male", "Female"),
                variable_name != "Cohort start date" | estimate_name %in% c("min", "max"),
                cdm_name != "CPRD Aurum"
)

CohortCharacteristics::tableCharacteristics(char, type = "flextable", header = c("cdm_name"), groupColumn = c("cohort_name"), hide = c("age_group_broad", "table_name", "value", "table", "window"))
```

## Figure 1 - Prior antibiotic use (-14 to -1)

```{r prior use, echo=FALSE, message = FALSE, warning = FALSE}
char_2 <- data[["summarise_characteristics"]] |>
  dplyr::filter(variable_name == "Antibiotics (-14 to -1)",
                strata_level == "overall") |>
  dplyr::mutate(
    group_level = stringr::str_replace(group_level, "^\\d+_", ""),
    group_level = stringr::str_to_sentence(group_level), # capitalize first letter
    variable_level = stringr::str_replace(variable_level, "^\\d+ ", ""),         # remove leading digits and underscore
    variable_level = stringr::str_to_sentence(variable_level), # capitalize first letter
    estimate_value = as.numeric(estimate_value)
  )

char_2_hosp <- char_2 |>
  dplyr::filter(cdm_name != "CPRD Aurum",
                estimate_name == "percentage",
                estimate_value >= 5, 
                group_level %in% c("Ciprofloxacin", "Clarithromycin", "Piperacillin", "Ceftriaxone",
                                   "Teicoplanin", "Vancomycin", "Cefuroxime"))

char_2_gp <- char_2 |>
  dplyr::filter(cdm_name == "CPRD Aurum",
                estimate_name == "percentage",
                estimate_value >= 5, 
                group_level %in% c("Ciprofloxacin", "Clarithromycin", "Erythromycin", "Fusidate"))

ggplot2::ggplot(char_2_hosp, ggplot2::aes(x = group_level, y = estimate_value, fill = variable_level)) +
  ggplot2::geom_bar(stat = "identity", colour = "black", position = "dodge") +
  ggplot2::facet_wrap(~ cdm_name, scales = "free", nrow = 2) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 60, vjust = 1, hjust = 1)
  ) +
  ggplot2::xlab("Database") +
  ggplot2::ylab("Proportion of individuals (%)") +
  ggplot2::labs(fill = "Access antibiotics") +
  paletteer::scale_fill_paletteer_d("MoMAColors::Lupi")
  
  ggplot2::ggplot(char_2_gp, ggplot2::aes(x = group_level, y = estimate_value, fill = variable_level)) +
  ggplot2::geom_bar(stat = "identity", colour = "black", position = "dodge") +
  ggplot2::facet_wrap(~ cdm_name, scales = "free", nrow = 2) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 60, vjust = 1, hjust = 1)
  ) +
  ggplot2::xlab("Database") +
  ggplot2::ylab("Proportion of individuals (%)") +
  ggplot2::labs(fill = "Access antibiotics") +
  paletteer::scale_fill_paletteer_d("MoMAColors::Lupi")
```

## Figure 3 - Indications

```{r indications, echo=FALSE, message = FALSE, warning = FALSE}
char_3 <- data[["summarise_characteristics"]] |>
  dplyr::filter(variable_name == "Indication flag",
                strata_level == "overall") |>
  dplyr::mutate(cdm_name = dplyr::case_when(
    cdm_name == "IDRIL_1" ~ "Lancs",
    cdm_name == "LTHT" ~ "Leeds",
    cdm_name == "Barts Health" ~ "Barts",
    cdm_name == "AurumCDM_202409" ~ "CPRD Aurum",
    cdm_name == "GOSH DRE" ~ "GOSH",
    .default = cdm_name
  ),
    group_level = stringr::str_replace(group_level, "^\\d+_", ""),         # remove leading digits and underscore
    group_level = stringr::str_to_sentence(group_level), # capitalize first letter
    variable_level = stringr::str_replace(variable_level, "^\\d+ ", ""),         # remove leading digits and underscore
    variable_level = stringr::str_to_sentence(variable_level), # capitalize first letter
    estimate_value = as.numeric(estimate_value)
  )

char_3_hosp <- char_3 |>
  dplyr::filter(estimate_name == "percentage",
                estimate_value >= 5,
                !variable_level %in% c("Signs and symptoms", "Bacterial infection"),
                group_level %in% c("Ciprofloxacin", "Clarithromycin", "Piperacillin", "Ceftriaxone",
                                   "Teicoplanin", "Vancomycin", "Cefuroxime"),
                cdm_name != "CPRD Aurum") |>
  dplyr::group_by(cdm_name, group_level) |>
  dplyr::slice_max(order_by = estimate_value, n = 3, with_ties = FALSE)

char_3_gp <- char_3 |>
  dplyr::filter(estimate_name == "percentage",
                estimate_value >= 5,
                !variable_level %in% c("Signs and symptoms", "Bacterial infection"),
                group_level %in% c("Ciprofloxacin", "Clarithromycin", "Erythromycin", "Fusidate"),
                cdm_name == "CPRD Aurum") |>
  dplyr::group_by(cdm_name, group_level) |>
  dplyr::slice_max(order_by = estimate_value, n = 3, with_ties = FALSE)

ggplot2::ggplot(char_3_hosp, ggplot2::aes(x = group_level, y = estimate_value, fill = variable_level)) +
  ggplot2::geom_bar(stat = "identity", colour = "black", position = "dodge") +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 60, vjust = 1, hjust = 1)
  ) +
  ggplot2::xlab("Watch Antibiotics") +
  ggplot2::ylab("Proportion of individuals (%)") +
  ggplot2::labs(fill = "Indications") +
    ggplot2::coord_flip() +
  paletteer::scale_fill_paletteer_d("MoMAColors::Lupi")

ggplot2::ggplot(char_3_gp, ggplot2::aes(x = group_level, y = estimate_value, fill = variable_level)) +
  ggplot2::geom_bar(stat = "identity", colour = "black", position = "dodge") +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 60, vjust = 1, hjust = 1)
  ) +
  ggplot2::xlab("Watch Antibiotics") +
  ggplot2::ylab("Proportion of individuals (%)") +
  ggplot2::labs(fill = "Indications") +
    ggplot2::coord_flip() +
  paletteer::scale_fill_paletteer_d("MoMAColors::Lupi")
```

## Figure 4 - Incidence of Ciprofloxacin Use

```{r incidence, echo=FALSE, message = FALSE, warning = FALSE}
inc <- data[["incidence"]] |>
  dplyr::filter(estimate_name == "incidence_100000_pys") |>
  omopgenerics::splitAdditional() |>
  omopgenerics::splitGroup() |>
  omopgenerics::addSettings() |>
  dplyr::filter(denominator_age_group %in% c("0 to 150"),
                denominator_days_prior_observation == "0",
                denominator_sex == "Both",
                analysis_interval == "quarters") |>
  dplyr::mutate(
    outcome_cohort_name = stringr::str_replace(outcome_cohort_name, "^\\d+_", ""),         # remove leading digits and underscore
    outcome_cohort_name = stringr::str_to_sentence(outcome_cohort_name), # capitalize first letter
    estimate_value = as.numeric(estimate_value)
  ) |>
  dplyr::filter(!incidence_start_date %in% c("2025-04-01", "2025-01-01"))

inc_hosp <- inc |>
  dplyr::filter(cdm_name != "CPRD Aurum",
                outcome_cohort_name %in% c("Ciprofloxacin", "Clarithromycin", "Piperacillin", "Ceftriaxone",
                                   "Teicoplanin", "Vancomycin", "Cefuroxime"))
inc_gp <- inc |>
  dplyr::filter(cdm_name == "CPRD Aurum",
                outcome_cohort_name %in% c("Ciprofloxacin", "Clarithromycin", "Erythromycin", "Fusidate"))

ggplot2::ggplot(inc_hosp, ggplot2::aes(x = incidence_start_date, y = estimate_value, colour = outcome_cohort_name, group = outcome_cohort_name)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme_minimal() +
  ggplot2::theme(axis.text.x = ggplot2::element_blank()) +
  paletteer::scale_colour_paletteer_d("MoMAColors::Lupi")

ggplot2::ggplot(inc_gp, ggplot2::aes(x = incidence_start_date, y = estimate_value, colour = outcome_cohort_name, group = outcome_cohort_name)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme_minimal() +
  ggplot2::theme(axis.text.x = ggplot2::element_blank()) +
  paletteer::scale_colour_paletteer_d("MoMAColors::Lupi")
  
```

## Figure 5 

```{r incidence 2, echo=FALSE, message = FALSE, warning = FALSE}
inc_sex <- data[["incidence"]] |>
  dplyr::filter(estimate_name == "incidence_100000_pys") |>
  omopgenerics::splitAdditional() |>
  omopgenerics::splitGroup() |>
  omopgenerics::addSettings() |>
  dplyr::filter(denominator_age_group == "0 to 150",
                denominator_days_prior_observation == "0",
                analysis_interval == "quarters") |>
  dplyr::mutate(
    outcome_cohort_name = stringr::str_replace(outcome_cohort_name, "^\\d+_", ""),         # remove leading digits and underscore
    outcome_cohort_name = stringr::str_to_sentence(outcome_cohort_name), # capitalize first letter
    estimate_value = as.numeric(estimate_value)
  ) |>
  dplyr::filter(!incidence_start_date %in% c("2025-04-01", "2025-01-01"))

inc_sex_hosp <- inc_sex |>
  dplyr::filter(cdm_name != "CPRD Aurum",
                outcome_cohort_name == "Ciprofloxacin",
                denominator_sex != "Both")

ggplot2::ggplot(inc_sex_hosp, ggplot2::aes(x = incidence_start_date, y = estimate_value, colour = denominator_sex, group = denominator_sex)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme_minimal() +
  ggplot2::theme(axis.text.x = ggplot2::element_blank()) 

inc_sex_gp <- inc_sex |>
  dplyr::filter(cdm_name == "CPRD Aurum",
                outcome_cohort_name %in% c("Ciprofloxacin"),
                denominator_sex != "Both")

ggplot2::ggplot(inc_sex_gp, ggplot2::aes(x = incidence_start_date, y = estimate_value, colour = denominator_sex, group = denominator_sex)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~ outcome_cohort_name, scales = "free") +
  ggplot2::theme_minimal() +
  ggplot2::theme(axis.text.x = ggplot2::element_blank()) 
```

```{r incidence 3, echo=FALSE, message = FALSE, warning = FALSE}
inc_age <- data[["incidence"]] |>
  dplyr::filter(estimate_name == "incidence_100000_pys") |>
  omopgenerics::splitAdditional() |>
  omopgenerics::splitGroup() |>
  omopgenerics::addSettings() |>
  dplyr::filter(denominator_age_group != "0 to 150",
                denominator_sex == "Both",
                denominator_days_prior_observation == "0",
                analysis_interval == "quarters") |>
  dplyr::mutate(
    outcome_cohort_name = stringr::str_replace(outcome_cohort_name, "^\\d+_", ""),         # remove leading digits and underscore
    outcome_cohort_name = stringr::str_to_sentence(outcome_cohort_name),
    estimate_value = as.numeric(estimate_value)
  ) |>
  dplyr::filter(outcome_cohort_name == "Ciprofloxacin") |>
  dplyr::filter(!incidence_start_date %in% c("2025-04-01", "2025-01-01"))

inc_age_ped <- inc_age |>
  dplyr::filter(cdm_name == "GOSH",
                denominator_age_group %in% c("0 to 4", "5 to 9", "10 to 14", "15 to 18"))

inc_age_hosp <- inc_age |>
  dplyr::filter(!cdm_name %in% c("GOSH", "CPRD Aurum"),
                denominator_age_group %in% c("65 to 150"))

inc_age_gp <- inc_age |>
  dplyr::filter(cdm_name =="CPRD Aurum",
                denominator_age_group %in% c("65 to 150"))

ggplot2::ggplot(inc_age_ped, ggplot2::aes(x = incidence_start_date, y = estimate_value, colour = denominator_age_group, group = denominator_age_group)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme(axis.text.x = ggplot2::element_blank()) 

ggplot2::ggplot(inc_age_hosp, ggplot2::aes(x = incidence_start_date, y = estimate_value, colour = denominator_age_group, group = denominator_age_group)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme(axis.text.x = ggplot2::element_blank()) 

ggplot2::ggplot(inc_age_gp, ggplot2::aes(x = incidence_start_date, y = estimate_value, colour = denominator_age_group, group = denominator_age_group)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::theme_minimal() +
  ggplot2::facet_wrap(~ cdm_name, scales = "free") +
  ggplot2::theme(axis.text.x = ggplot2::element_blank()) 
```

