# Generated by OmopViewer 0.2.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      omopgenerics::exportSummarisedResult(data, fileName = file)
    }
  )
  # summarise_omop_snapshot -----
  ## tidy summarise_omop_snapshot -----
  getTidyDataSummariseOmopSnapshot <- shiny::reactive({
    res <- data |>
      filterData("summarise_omop_snapshot", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_omop_snapshot_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]
    
    # pivot
    pivot <- input$summarise_omop_snapshot_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseOmopSnapshot(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_omop_snapshot.csv",
    content = function(file) {
      getTidyDataSummariseOmopSnapshot() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_omop_snapshot -----
  ## output 17 -----
  createOutput17 <- shiny::reactive({
    result <- data |>
      filterData("summarise_omop_snapshot", input)
    OmopSketch::tableOmopSnapshot(
      result
    )
  })
  output$summarise_omop_snapshot_gt_17 <- gt::render_gt({
    createOutput17()
  })
  output$summarise_omop_snapshot_gt_17_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_omop_snapshot.", input$summarise_omop_snapshot_gt_17_download_type),
    content = function(file) {
      obj <- createOutput17()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  
  # summarise_observation_period -----
  ## tidy summarise_observation_period -----
  getTidyDataSummariseObservationPeriod <- shiny::reactive({
    res <- data |>
      filterData("summarise_observation_period", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_observation_period_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]
    
    # pivot
    pivot <- input$summarise_observation_period_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_observation_period_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseObservationPeriod(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_observation_period_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_observation_period.csv",
    content = function(file) {
      getTidyDataSummariseObservationPeriod() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_observation_period -----
  ## output 15 -----
  createOutput15 <- shiny::reactive({
    result <- data |>
      filterData("summarise_observation_period", input)
    OmopSketch::tableObservationPeriod(
      result
    )
  })
  output$summarise_observation_period_gt_15 <- gt::render_gt({
    createOutput15()
  })
  output$summarise_observation_period_gt_15_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_observation_period.", input$summarise_observation_period_gt_15_download_type),
    content = function(file) {
      obj <- createOutput15()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## output 16 -----
  createOutput16 <- shiny::reactive({
    result <- data |>
      filterData("summarise_observation_period", input)
    OmopSketch::plotObservationPeriod(
      result,
      variableName = input$summarise_observation_period_ggplot2_16_variableName,
      plotType = input$summarise_observation_period_ggplot2_16_plotType,
      facet = input$summarise_observation_period_ggplot2_16_facet
    )
  })
  output$summarise_observation_period_ggplot2_16 <- shiny::renderPlot({
    createOutput16()
  })
  output$summarise_observation_period_ggplot2_16_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_observation_period.", "png"),
    content = function(file) {
      obj <- createOutput16()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_observation_period_ggplot2_16_download_width),
        height = as.numeric(input$summarise_observation_period_ggplot2_16_download_height),
        units = input$summarise_observation_period_ggplot2_16_download_units,
        dpi = as.numeric(input$summarise_observation_period_ggplot2_16_download_dpi)
      )
    }
  )

  ## output summarise_cohort_count -----
  ## output 9 -----
  createOutput9 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::tableCohortCount(
      result,
      header = input$summarise_cohort_count_gt_9_header,
      groupColumn = input$summarise_cohort_count_gt_9_groupColumn,
      hide = input$summarise_cohort_count_gt_9_hide
    )
  })
  output$summarise_cohort_count_gt_9 <- gt::render_gt({
    createOutput9()
  })
  output$summarise_cohort_count_gt_9_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_count.", input$summarise_cohort_count_gt_9_download_type),
    content = function(file) {
      obj <- createOutput9()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## output 10 -----
  createOutput10 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::plotCohortCount(
      result,
      facet = input$summarise_cohort_count_ggplot2_10_facet,
      colour = input$summarise_cohort_count_ggplot2_10_colour
    )
  })
  output$summarise_cohort_count_ggplot2_10 <- shiny::renderPlot({
    createOutput10()
  })
  output$summarise_cohort_count_ggplot2_10_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_count.", "png"),
    content = function(file) {
      obj <- createOutput10()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_count_ggplot2_10_download_width),
        height = as.numeric(input$summarise_cohort_count_ggplot2_10_download_height),
        units = input$summarise_cohort_count_ggplot2_10_download_units,
        dpi = as.numeric(input$summarise_cohort_count_ggplot2_10_download_dpi)
      )
    }
  )
  
  # summarise_characteristics -----
  ## tidy summarise_characteristics -----
  getTidyDataSummariseCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_characteristics", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]
    
    # pivot
    pivot <- input$summarise_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_characteristics -----
  ## output 7 -----
  createOutput7 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input) |>
      dplyr::filter(!variable_name %in% c("Access antibiotics (-14 to -1)",
                                          "Watch antibiotics (-14 to -1)",
                                          "Indication flag"))
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_7_header,
      groupColumn = input$summarise_characteristics_gt_7_groupColumn,
      hide = input$summarise_characteristics_gt_7_hide
    )
  })
  output$summarise_characteristics_gt_7 <- gt::render_gt({
    createOutput7()
  })
  output$summarise_characteristics_gt_7_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_7_download_type),
    content = function(file) {
      obj <- createOutput7()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## output prior use -----
  ## output 10 -----
  createOutput10 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input) |>
      dplyr::filter(variable_name %in% c("Access antibiotics (-14 to -1)",
                                          "Watch antibiotics (-14 to -1)"))
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_10_header,
      groupColumn = input$summarise_characteristics_gt_10_groupColumn,
      hide = input$summarise_characteristics_gt_10_hide
    )
  })
  output$summarise_characteristics_gt_10 <- gt::render_gt({
    createOutput10()
  })
  output$summarise_characteristics_gt_10_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_10_download_type),
    content = function(file) {
      obj <- createOutput10()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## output prior use -----
  ## output 10 -----
  createOutput11 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input) |>
      dplyr::filter(variable_name %in% c("Indication flag"))
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_11_header,
      groupColumn = input$summarise_characteristics_gt_11_groupColumn,
      hide = input$summarise_characteristics_gt_11_hide
    )
  })
  output$summarise_characteristics_gt_11 <- gt::render_gt({
    createOutput11()
  })
  output$summarise_characteristics_gt_11_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_11_download_type),
    content = function(file) {
      obj <- createOutput11()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## output 8 -----
  createOutput8 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    CohortCharacteristics::plotCharacteristics(
      result,
      plotStyle = input$summarise_characteristics_ggplot2_8_plotStyle,
      facet = input$summarise_characteristics_ggplot2_8_facet,
      colour = input$summarise_characteristics_ggplot2_8_colour
    )
  })
  output$summarise_characteristics_ggplot2_8 <- shiny::renderPlot({
    createOutput8()
  })
  output$summarise_characteristics_ggplot2_8_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_characteristics.", "png"),
    content = function(file) {
      obj <- createOutput8()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_characteristics_ggplot2_8_download_width),
        height = as.numeric(input$summarise_characteristics_ggplot2_8_download_height),
        units = input$summarise_characteristics_ggplot2_8_download_units,
        dpi = as.numeric(input$summarise_characteristics_ggplot2_8_download_dpi)
      )
    }
  )
  
  
  # summarise_large_scale_characteristics -----
  ## tidy summarise_large_scale_characteristics -----
  getTidyDataSummariseLargeScaleCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_large_scale_characteristics", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_large_scale_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]
    
    # pivot
    pivot <- input$summarise_large_scale_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_large_scale_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseLargeScaleCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_large_scale_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_large_scale_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseLargeScaleCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_large_scale_characteristics -----
  ## output 0 -----
  createOutput0 <- shiny::reactive({
    result <- data |>
      filterData("summarise_large_scale_characteristics", input)
    simpleTable(
      result,
      header = input$summarise_large_scale_characteristics_gt_0_header,
      group = input$summarise_large_scale_characteristics_gt_0_group,
      hide = input$summarise_large_scale_characteristics_gt_0_hide
    )
  })
  output$summarise_large_scale_characteristics_gt_0 <- gt::render_gt({
    createOutput0()
  })
  output$summarise_large_scale_characteristics_gt_0_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_large_scale_characteristics.", input$summarise_large_scale_characteristics_gt_0_download_type),
    content = function(file) {
      obj <- createOutput0()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  
  # incidence -----
  ## tidy incidence -----
  getTidyDataIncidence <- shiny::reactive({
    res <- data |>
      filterData("incidence", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")
    
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$incidence_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]
    
    # pivot
    pivot <- input$incidence_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
                     "estimates" = "estimate_name",
                     "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }
    
    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$incidence_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataIncidence(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$incidence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_incidence.csv",
    content = function(file) {
      getTidyDataIncidence() |>
        readr::write_csv(file = file)
    }
  )
  ## output incidence -----
  ## output 18 -----
  createOutput18 <- shiny::reactive({
    result <- data |>
      filterData("incidence", input)
    IncidencePrevalence::tableIncidence(
      result,
      header = input$incidence_gt_18_header,
      groupColumn = input$incidence_gt_18_groupColumn,
      hide = input$incidence_gt_18_hide
    )
  })
  output$incidence_gt_18 <- gt::render_gt({
    createOutput18()
  })
  output$incidence_gt_18_download <- shiny::downloadHandler(
    filename = paste0("output_gt_incidence.", input$incidence_gt_18_download_type),
    content = function(file) {
      obj <- createOutput18()
      gt::gtsave(data = obj, filename = file)
    }
  )
  
  ## output 19 -----
  createOutput19 <- shiny::reactive({
    result <- data |>
      filterData("incidence", input)
    IncidencePrevalence::plotIncidence(
      result,
      x = input$incidence_ggplot2_19_x,
      ribbon = input$incidence_ggplot2_19_ribbon,
      facet = input$incidence_ggplot2_19_facet,
      colour = input$incidence_ggplot2_19_colour
    )
  })
  output$incidence_ggplot2_19 <- shiny::renderPlot({
    createOutput19()
  })
  output$incidence_ggplot2_19_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_incidence.", "png"),
    content = function(file) {
      obj <- createOutput19()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$incidence_ggplot2_19_download_width),
        height = as.numeric(input$incidence_ggplot2_19_download_height),
        units = input$incidence_ggplot2_19_download_units,
        dpi = as.numeric(input$incidence_ggplot2_19_download_dpi)
      )
    }
  )
  
  ## output 19 -----
  createOutput20 <- shiny::reactive({
    result <- data |>
      filterData("incidence", input)
    IncidencePrevalence::plotIncidencePopulation(
      result,
      x = input$incidence_ggplot2_20_x,
      y = input$incidence_ggplot2_20_y,
      facet = input$incidence_ggplot2_20_facet,
      colour = input$incidence_ggplot2_20_colour
    )
  })
  output$incidence_ggplot2_20 <- shiny::renderPlot({
    createOutput20()
  })
  output$incidence_ggplot2_20_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_incidence_population.", "png"),
    content = function(file) {
      obj <- createOutput20()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$incidence_ggplot2_20_download_width),
        height = as.numeric(input$incidence_ggplot2_20_download_height),
        units = input$incidence_ggplot2_20_download_units,
        dpi = as.numeric(input$incidence_ggplot2_20_download_dpi)
      )
    }
  )
}
