# Generated by OmopViewer 0.2.0
# Be careful editing this file
source("background.R")
ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hdruk_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(preset = "cerulean"),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    backgroundCard("background.md")
  ),
  # bslib::nav_panel(
  #   title = "Summary",
  #   icon = shiny::icon("file-alt"),
  #   summaryCard(data)
  # ),
  bslib::nav_menu(
    title = "Database details",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("clipboard-list"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_omop_snapshot_grouping_cdm_name,
                selected = filterValues$summarise_omop_snapshot_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_omop_snapshot_variable_name,
                selected = filterValues$summarise_omop_snapshot_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_omop_snapshot_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_omop_snapshot_estimate_name,
                selected = filterValues$summarise_omop_snapshot_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_omop_snapshot_tidy_columns,
                    selected = filterValues$summarise_omop_snapshot_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_omop_snapshot_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_omop_snapshot_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Snapshot table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_gt_17_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_17_download", label = "Download")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_omop_snapshot_gt_17")
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Observation period",
      icon = shiny::icon("eye"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_observation_period_grouping_cdm_name,
                selected = filterValues$summarise_observation_period_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_grouping_observation_period_ordinal",
                label = "Observation period ordinal",
                choices = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
                selected = filterValues$summarise_observation_period_grouping_observation_period_ordinal,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_observation_period_variable_name,
                selected = filterValues$summarise_observation_period_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_observation_period_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_observation_period_estimate_name,
                selected = filterValues$summarise_observation_period_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_observation_period_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_observation_period_tidy_columns,
                    selected = filterValues$summarise_observation_period_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_observation_period_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_observation_period_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_gt_15_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_gt_15_download", label = "Download")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_gt_15")
            )
          ),
          bslib::nav_panel(
            title = "Plot observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_ggplot2_16_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_ggplot2_16_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_variableName",
                    label = "variableName",
                    choices = "Number subjects",
                    selected = "Number subjects",
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_plotType",
                    label = "plotType",
                    selected = "barplot",
                    multiple = ,
                    choices = c("barplot", "boxplot", "densityplot"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_ggplot2_16_facet",
                    label = "facet",
                    selected = "cdm_name",
                    multiple = TRUE,
                    choices = c("cdm_name", "observation_period_ordinal"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_observation_period_ggplot2_16")
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Cohort details",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort count",
      icon = shiny::icon("users"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_settings_table_name",
                label = "Table name",
                choices = "antibiotics",
                selected = "antibiotics",
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_cohort_count_grouping_cdm_name,
                selected = filterValues$summarise_cohort_count_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_cohort_count_grouping_cohort_name,
                selected = filterValues$summarise_cohort_count_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_cohort_count_variable_name,
                selected = "Number records",
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_cohort_count_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_cohort_count_estimate_name,
                selected = filterValues$summarise_cohort_count_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table cohort count",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_gt_9_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_gt_9_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("cdm_name", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_cohort_count_gt_9_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "cohort_name",
                      input_id = "summarise_cohort_count_gt_9_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = character(),
                      input_id = "summarise_cohort_count_gt_9_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_cohort_count_gt_9_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_count_gt_9")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot cohort count",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_cohort_count_ggplot2_10_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_count_ggplot2_10_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_facet",
                    label = "facet",
                    selected = "cdm_name",
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_count_ggplot2_10_colour",
                    label = "colour",
                    selected = "cohort_name",
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_cohort_count_ggplot2_10")
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_settings_table_name",
                label = "Table name",
                choices = filterValues$summarise_characteristics_settings_table_name,
                selected = filterValues$summarise_characteristics_settings_table_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_characteristics_grouping_cdm_name,
                selected = filterValues$summarise_characteristics_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_characteristics_grouping_cohort_name,
                selected = filterValues$summarise_characteristics_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_grouping_age_group_broad",
                label = "Age group broad",
                choices = filterValues$summarise_characteristics_grouping_age_group_broad,
                selected = "overall",
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_characteristics_variable_name,
                selected = filterValues$summarise_characteristics_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_characteristics_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_characteristics_estimate_name,
                selected = filterValues$summarise_characteristics_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_characteristics_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_characteristics_tidy_columns,
                    selected = filterValues$summarise_characteristics_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_characteristics_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_characteristics_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Cohort characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_gt_7_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_gt_7_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("sex", "age_group_narrow", "age_group_broad", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_gt_7_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_gt_7_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_7_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_7_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_gt_7")
              )
            )
          ),
          bslib::nav_panel(
            title = "Prior antibiotic use",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_gt_10_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_gt_10_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("sex", "age_group_narrow", "age_group_broad", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_gt_10_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_gt_10_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_10_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_10_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_gt_10")
              )
            )
          ),
          bslib::nav_panel(
            title = "Outcomes of interest",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_gt_11_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_gt_11_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("sex", "age_group_narrow", "age_group_broad", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_gt_11_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_gt_11_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_11_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_characteristics_gt_11_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_gt_11")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_ggplot2_8_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_ggplot2_8_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_plotStyle",
                    label = "plotStyle",
                    selected = "barplot",
                    multiple = FALSE,
                    choices = c("boxplot", "barplot", "scatterplot"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_facet",
                    label = "facet",
                    selected = c("cohort_name", "cdm_name"),
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "sex", "age_group_narrow", "age_group_broad", "variable_name", "variable_level", "estimate_name", "table_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_ggplot2_8_colour",
                    label = "colour",
                    selected = "variable_level",
                    multiple = TRUE,
                    choices = c("cdm_name", "cohort_name", "sex", "age_group_narrow", "age_group_broad", "variable_name", "variable_level", "estimate_name", "table_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("summarise_characteristics_ggplot2_8")
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Large Scale Characteristics",
      icon = shiny::icon("arrow-up-right-dots"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_analysis",
                label = "Analysis",
                choices = filterValues$summarise_large_scale_characteristics_settings_analysis,
                selected = filterValues$summarise_large_scale_characteristics_settings_analysis,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_table_name",
                label = "Table name",
                choices = filterValues$summarise_large_scale_characteristics_settings_table_name,
                selected = filterValues$summarise_large_scale_characteristics_settings_table_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_settings_type",
                label = "Type",
                choices = filterValues$summarise_large_scale_characteristics_settings_type,
                selected = filterValues$summarise_large_scale_characteristics_settings_type,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$summarise_large_scale_characteristics_grouping_cdm_name,
                selected = filterValues$summarise_large_scale_characteristics_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_cohort_name",
                label = "Cohort name",
                choices = filterValues$summarise_large_scale_characteristics_grouping_cohort_name,
                selected = filterValues$summarise_large_scale_characteristics_grouping_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_grouping_concept_id",
                label = "Concept id",
                choices = filterValues$summarise_large_scale_characteristics_grouping_concept_id,
                selected = filterValues$summarise_large_scale_characteristics_grouping_concept_id,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_variable_name",
                label = "Variable name",
                choices = filterValues$summarise_large_scale_characteristics_variable_name,
                selected = filterValues$summarise_large_scale_characteristics_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_variable_level",
                label = "Variable level",
                choices = filterValues$summarise_large_scale_characteristics_variable_level,
                selected = filterValues$summarise_large_scale_characteristics_variable_level,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "summarise_large_scale_characteristics_estimate_name",
                label = "Estimate name",
                choices = filterValues$summarise_large_scale_characteristics_estimate_name,
                selected = filterValues$summarise_large_scale_characteristics_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_tidy_columns",
                    label = "Columns",
                    choices = filterValues$summarise_large_scale_characteristics_tidy_columns,
                    selected = filterValues$summarise_large_scale_characteristics_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "summarise_large_scale_characteristics_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("summarise_large_scale_characteristics_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Formatted",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_large_scale_characteristics_gt_0_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "summarise_large_scale_characteristics_gt_0_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("concept_id", "variable_name", "variable_level", "estimate_name", "analysis", "table_name", "type"),
                      input_id = "summarise_large_scale_characteristics_gt_0_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "cdm_name",
                      input_id = "summarise_large_scale_characteristics_gt_0_header"
                    ),
                    sortable::add_rank_list(
                      text = "group",
                      labels = "cohort_name",
                      input_id = "summarise_large_scale_characteristics_gt_0_group"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = character(),
                      input_id = "summarise_large_scale_characteristics_gt_0_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_large_scale_characteristics_gt_0")
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Incidence",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Incidence",
      icon = shiny::icon("chart-line"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::accordion(
            bslib::accordion_panel(
              title = "Settings",
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_analysis_complete_database_intervals",
                label = "Analysis complete database intervals",
                choices = filterValues$incidence_settings_analysis_complete_database_intervals,
                selected = filterValues$incidence_settings_analysis_complete_database_intervals,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_analysis_outcome_washout",
                label = "Analysis outcome washout",
                choices = filterValues$incidence_settings_analysis_outcome_washout,
                selected = filterValues$incidence_settings_analysis_outcome_washout,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_analysis_repeated_events",
                label = "Analysis repeated events",
                choices = filterValues$incidence_settings_analysis_repeated_events,
                selected = filterValues$incidence_settings_analysis_repeated_events,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_age_group",
                label = "Denominator age group",
                choices = filterValues$incidence_settings_denominator_age_group,
                selected = c("0 to 150","0 to 19", "20 to 64", "65 to 150"),
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_days_prior_observation",
                label = "Denominator days prior observation",
                choices = filterValues$incidence_settings_denominator_days_prior_observation,
                selected = "0",
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_end_date",
                label = "Denominator end date",
                choices = filterValues$incidence_settings_denominator_end_date,
                selected = filterValues$incidence_settings_denominator_end_date,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_requirements_at_entry",
                label = "Denominator requirements at entry",
                choices = filterValues$incidence_settings_denominator_requirements_at_entry,
                selected = filterValues$incidence_settings_denominator_requirements_at_entry,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_sex",
                label = "Denominator sex",
                choices = filterValues$incidence_settings_denominator_sex,
                selected = "Both",
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_start_date",
                label = "Denominator start date",
                choices = filterValues$incidence_settings_denominator_start_date,
                selected = filterValues$incidence_settings_denominator_start_date,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_target_cohort_name",
                label = "Denominator target cohort name",
                choices = filterValues$incidence_settings_denominator_target_cohort_name,
                selected = filterValues$incidence_settings_denominator_target_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_settings_denominator_time_at_risk",
                label = "Denominator time at risk",
                choices = filterValues$incidence_settings_denominator_time_at_risk,
                selected = filterValues$incidence_settings_denominator_time_at_risk,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Grouping",
              shinyWidgets::pickerInput(
                inputId = "incidence_grouping_cdm_name",
                label = "Cdm name",
                choices = filterValues$incidence_grouping_cdm_name,
                selected = filterValues$incidence_grouping_cdm_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_grouping_denominator_cohort_name",
                label = "Denominator cohort name",
                choices = filterValues$incidence_grouping_denominator_cohort_name,
                selected = filterValues$incidence_grouping_denominator_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_grouping_outcome_cohort_name",
                label = "Outcome cohort name",
                choices = filterValues$incidence_grouping_outcome_cohort_name,
                selected = filterValues$incidence_grouping_outcome_cohort_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_grouping_incidence_start_date",
                label = "Incidence start date",
                choices = filterValues$incidence_grouping_incidence_start_date,
                selected = filterValues$incidence_grouping_incidence_start_date[
                  filterValues$incidence_grouping_incidence_start_date >= "2020-01-01" & 
                    filterValues$incidence_grouping_incidence_start_date <= "2024-12-31"],
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_grouping_incidence_end_date",
                label = "Incidence end date",
                choices = filterValues$incidence_grouping_incidence_end_date,
                selected = filterValues$incidence_grouping_incidence_end_date,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              ),
              shinyWidgets::pickerInput(
                inputId = "incidence_grouping_analysis_interval",
                label = "Analysis interval",
                choices = filterValues$incidence_grouping_analysis_interval,
                selected = "quarters",
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Variables",
              shinyWidgets::pickerInput(
                inputId = "incidence_variable_name",
                label = "Variable name",
                choices = filterValues$incidence_variable_name,
                selected = filterValues$incidence_variable_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            ),
            bslib::accordion_panel(
              title = "Estimates",
              shinyWidgets::pickerInput(
                inputId = "incidence_estimate_name",
                label = "Estimate name",
                choices = filterValues$incidence_estimate_name,
                selected = filterValues$incidence_estimate_name,
                multiple = TRUE,
                options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
              )
            )
          )
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "incidence_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "incidence_tidy_columns",
                    label = "Columns",
                    choices = filterValues$incidence_tidy_columns,
                    selected = filterValues$incidence_tidy_columns,
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::radioButtons(
                    inputId = "incidence_tidy_pivot",
                    label = "Pivot estimates/variables",
                    choices = c("none", "estimates", "estimates and variables"),
                    selected = "none"
                  ),
                  position = "right"
                ),
                DT::dataTableOutput("incidence_tidy")
              )
            )
          ),
          bslib::nav_panel(
            title = "Table incidence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_gt_18_download_type",
                    label = "File type",
                    selected = "docx",
                    choices = c("docx", "png", "pdf", "html"),
                    multiple = FALSE
                  ),
                  shiny::downloadButton(outputId = "incidence_gt_18_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "none",
                      labels = c("incidence_start_date", "incidence_end_date", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level"),
                      input_id = "incidence_gt_18_none"
                    ),
                    sortable::add_rank_list(
                      text = "header",
                      labels = "estimate_name",
                      input_id = "incidence_gt_18_header"
                    ),
                    sortable::add_rank_list(
                      text = "groupColumn",
                      labels = c("cdm_name", "outcome_cohort_name"),
                      input_id = "incidence_gt_18_groupColumn"
                    ),
                    sortable::add_rank_list(
                      text = "hide",
                      labels = c("denominator_cohort_name", "analysis_interval"),
                      input_id = "incidence_gt_18_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("incidence_gt_18")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot incidence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "incidence_ggplot2_19_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "incidence_ggplot2_19_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_19_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "incidence_ggplot2_19_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "incidence_ggplot2_19_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_19_x",
                    label = "x",
                    selected = "incidence_start_date",
                    multiple = FALSE,
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "incidence_ggplot2_19_ribbon",
                    label = "ribbon",
                    value = c(FALSE)
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_19_facet",
                    label = "facet",
                    selected = c("cdm_name","outcome_cohort_name"),
                    multiple = TRUE,
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_19_colour",
                    label = "colour",
                    selected = "denominator_age_group",
                    multiple = TRUE,
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("incidence_ggplot2_19")
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot incidence population",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "incidence_ggplot2_20_download_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "incidence_ggplot2_20_download_height",
                    label = "Height",
                    value = 10
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_20_download_units",
                    label = "Units",
                    selected = "cm",
                    choices = c("px", "cm", "inch"),
                    multiple = FALSE
                  ),
                  shiny::numericInput(
                    inputId = "incidence_ggplot2_20_download_dpi",
                    label = "dpi",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "incidence_ggplot2_20_download", label = "Download")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_20_y",
                    label = "y",
                    selected = "Incidence",
                    multiple = FALSE,
                    choices = c("incidence_100000_pys", "denominator_count", "person_years", "outcome_count"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_20_x",
                    label = "x",
                    selected = "incidence_start_date",
                    multiple = FALSE,
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_20_facet",
                    label = "facet",
                    selected = "cdm_name",
                    multiple = TRUE,
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "incidence_ggplot2_20_colour",
                    label = "colour",
                    selected = "outcome_cohort_name",
                    multiple = TRUE,
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "incidence_start_date", "incidence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_outcome_washout", "analysis_repeated_events", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level", "estimate_name"),
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::plotOutput("incidence_ggplot2_20")
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.2.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)